sudo: false
language: cpp

compiler:
    - clang
    - gcc

addons:
    apt:
        packages:
            # sfml-window
            - libx11-dev
            - libxcb1-dev
            - libx11-xbc-dev
            - libxcb-randr0-dev
            - libxcb-image0-dev
            - libgl1-mesa-dev
            - libudev-dev
            # sfml-graphics
            - libfreetype6-dev
            - libjpeg-dev
            # sfml-audio
            - libopenal-dev
            - libflac-dev
            - libvorbis-dev
            # cmake
            - cmake
before_script:
    - cmake .

install:
    - mkdir -p lib/SFML && cd lib/SFML 
    - wget https://github.com/SFML/SFML/archive/2.3.1.tar.gz
    - tar -xzvf
    - cd SFML-2.3.1 && cmake .
    - make install

script:
    - make

cache:
    - apt
