language: cpp

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq libsfml-dev
    - sudo apt-get install -qq freeglut3 freeglut3-dev binutils-gold

before_script:
    - cmake .

script:
    - make

