language: cpp

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq libsdl2-dev libsdl2-image-dev
    - sudo apt-get install -qq freeglut3 freeglut3-dev binutils-gold

before_script:
    - cmake .

script:
    - make

