language: cpp

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install -qq libsdl2-2.0 libsdl2-dev
    - sudo apt-get install -qq freeglut3 freeglut3-dev binutils-gold

before_script:
    - cmake .

script:
    - make

